### ISSUE TITLE
Fails to build yarl 1.9.4 with a Filename Too Long error

### ISSUE THREAD

**Issue by brianjmurrell** [befeleme/pyp2spec#44] opened 2024-02-08 15:15 UTC
The [`build.log`](https://github.com/befeleme/pyp2spec/files/14211018/build.log) because a paste of the text results in a comment > GH's 64K limit.

**Comment by hroncok** [comment] 2024-02-08 15:52
Could you attach the spec file? Looks like something is copying pyproject build dir into itself.

**Comment by brianjmurrell** [comment] 2024-02-08 16:01
[python-yarl.spec.txt](https://github.com/befeleme/pyp2spec/files/14211588/python-yarl.spec.txt)

**Comment by hroncok** [comment] 2024-02-08 16:05
The package uses a custom build backend. I suspect this might need fixing there. Anyway, it's not a bug in pyp2spec, most likely it's an issue that might need to be adressed in the implementation of %pyproject_wheel or the build backend of yarl. I'll have a look on the backend code later today.

**Comment by hroncok** [comment] 2024-02-08 18:07
This is the same problem that I fixed 4 years ago in pip: https://github.com/pypa/pip/issues/7872

**Comment by hroncok** [comment] 2024-02-08 18:23
Reported https://github.com/aio-libs/yarl/issues/992

**Comment by befeleme** [comment] 2024-02-15 12:52
Thank you, I'll close it here.

**Closed by befeleme** 2024-02-15 12:52 UTC
